### ISSUE TITLE
Command failed dot -Tpng

### ISSUE THREAD

**Issue by ArtemAdamenko** [ts-graphviz/node#25]
Hello!
For code below
`    await graphviz.exportToFile('digraph g { a -> b }', {
        format: "png",
        output: 'example.png',
    });`
i have a error
Uncaught Error: Command failed: dot -Tpng -o example.png /var/folders/yq/bxh3c38d5z9bc8zxtklmkkcm0000gn/T/tmp-16365-XTc0c1Fr1uTU

**Comment by kamiazya** [comment]
@ArtemAdamenko It did not occur in my environment.

Please give me as much information as you can reproduce, including OS, Node.js version, package version, and Module format.

**Comment by ArtemAdamenko** [comment]
`import * as graphviz from "@ts-graphviz/node";

(async function test() {
    let dot = 'digraph g { a -> b }';
    await graphviz.exportToFile('digraph g { a -> b }', {
        format: "png",
        output: 'example.png',
    });
})()`

macOs Monterey 12.5.1
Nodejs 16.14.2
"@ts-graphviz/node": "^0.4.1"
Module format default - im not setup module format in package.json

**Comment by kamiazya** [comment]
@ArtemAdamenko 
I tried to create a [reproducible environment](https://github.com/kamiazya/ts-graphviz-node-command-failed-reproduction), but it didn't seem to reproduce with only the information I could find.

Are there any other factors?

**Comment by kamiazya** [comment]
I don't own a macOS device, so I would appreciate your help in forking the repository to reproduce the phenomenon.

**Comment by kamiazya** [comment]
@ArtemAdamenko 

This project has been merged into [ts-graphviz](https://github.com/ts-graphviz/ts-graphviz).

When we migrated to ts-graphviz, we changed to a method that does not use temporary files, so we do not expect this problem to occur.

We recommend that you migrate to the adapter module of ts-graphviz.
